App\Entity\Tree:
  attributes:
    original:
      groups: [ 'tree' ]
    flattened:
      groups: [ 'tree', 'convert' ]
    depth:
      groups: [ 'tree', 'convert' ]
    created_at:
      groups: [ 'tree' ]

